### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by Sebush** [Clever-Labs/seo-checker#1]
i tried:
var seochecker = require('seo-checker');
var pageBody = seochecker.load('http://google.com');

TypeError: undefined is not a function
    at Request._callback (/home/SOLUTE/sh/website/py_frontend/nodejs/seo/node_modules/seo-checker/src/index.js:35:16)
    at Request.self.callback (/home/SOLUTE/sh/website/py_frontend/nodejs/seo/node_modules/seo-checker/node_modules/request/request.js:197:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/SOLUTE/sh/website/py_frontend/nodejs/seo/node_modules/seo-checker/node_modules/request/request.js:1050:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/SOLUTE/sh/website/py_frontend/nodejs/seo/node_modules/seo-checker/node_modules/request/request.js:996:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

**Comment by billpatrianakos** [comment]
The `.load` method requires a callback. Sorry about that. The README needs updating. The example just below that show correct usage of that function.
